"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let apple = "apple";
console.log("apple is equal to apple");
console.log(apple === "apple");
console.log("apple is not equal to apple");
console.log(apple !== "apple");
let uppercaseApple = "APPLE";
console.log("APPLE is equal to apple after converting to lowercase");
console.log(uppercaseApple.toLocaleLowerCase() == "apple");
console.log("APPLE is not equal to apple after converting to lowercase");
console.log(uppercaseApple.toLocaleLowerCase() !== "apple");
let ten = 10;
let twenty = 20;
console.log("ten is equal to twenty");
console.log(ten === twenty);
console.log("ten is not equal to twenty");
console.log(ten !== twenty);
console.log("twenty is less than ten");
console.log(twenty < ten);
console.log("twenty is greater than or equal to ten");
console.log(twenty >= ten);
console.log("twenty is not less than or equal to ten");
console.log(twenty <= ten);
console.log("twenty is not equal to ten and twenty isgreater than ten ");
console.log(twenty !== ten && twenty > ten);
console.log("twenty is not equal to ten and ten is greater than twenty ");
console.log(twenty !== ten && ten > twenty);
console.log("twenty is greater than ten or twenty is equal to twenty ");
console.log(twenty > ten || twenty == twenty);
console.log("twenty is less than ten or twenty is not equal to twenty ");
console.log(twenty < ten || twenty !== twenty);
let fruits = ["apple", "orange", "banana"];
console.log("orange is include in fruits array");
console.log(fruits.includes("orange"));
console.log("grape is  include in fruits array");
console.log(fruits.includes("grape"));
