"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let addition = 6 + 2;
let subtraction = 10 - 2;
let multiplication = 4 * 2;
let division = 16 / 2;
console.log(addition);
console.log(subtraction);
console.log(multiplication);
console.log(division);
